name: Funky Cat Animation üê±

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate contribution animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: MayMonKo
          outputs: |
               dist/cat.svg?color_snake=#ec4899&color_dots=#00000000
               dist/cat-dark.svg?palette=github-dark&color_snake=#f472b6&color_dots=#00000000

      - name: Publish animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
